Feature/hosiptal registration in pharmacy
PSW-2020-ORG10/HealthcareSystem pull request #11
Opened 2020-11-20 20:17 UTC by tamaragovorcin

2020-11-20 21:53 UTC, Maja0505 commented on IntegrationWithPharmacies/Controllers/VueHelper.cs
> +        }
It is necessary to refactor this functionality

2020-11-20 22:35 UTC, Nemanja0505 commented on IntegrationWithPharmacies/Controllers/RegistrationController.cs
> +            return Ok(result);
Unnecessary instance of List<RegistrationInPharmacy>, you should return it directly through the Ok() method.
return Ok(registrationInPharmacyService.GetAll())

2020-11-20 22:40 UTC, Nemanja0505 commented on IntegrationWithPharmacies/Controllers/RegistrationController.cs
> +            return Ok();
Unnecessary instance of object, use it directly in the if statement.

2020-11-20 22:45 UTC, Maja0505 commented on IntegrationWithPharmacies/Startup.cs
> +            options.UseMySql(ConfigurationExtensions.GetConnectionString(Configuration, "MyDbContextConnectionString")).UseLazyLoadingProxies());
Use same form as in 30. and 31.  lines

2020-11-20 22:46 UTC, Maja0505 commented on IntegrationWithPharmacies/Startup.cs
> +            });
Use same form as in 30. and 31.  lines

2020-11-20 22:49 UTC, Nemanja0505 commented on PatientWebApplication/HealthClinic.DAL/Adapters/RegistrationInPharmacyAdapter.cs
> +            return registration;
Unnecessary instance of object, return it directly.

2020-11-20 22:49 UTC, Nemanja0505 commented on PatientWebApplication/HealthClinic.DAL/Adapters/RegistrationInPharmacyAdapter.cs
> +            return dto;
Unnecessary instance of object, return it directly.

2020-11-20 22:53 UTC, Nemanja0505 requested changes
Fix commented parts of code.

2020-11-20 22:54 UTC, Maja0505 requested changes
Fix commented parts of code

2020-11-21 16:02 UTC, Maja0505 approved these changes
PR is approved. The task solution is implemented with good Clean code principles.

2020-11-21 17:39 UTC, Nemanja0505 approved these changes
PR is approved. The task solution is implemented with good Clean code principles.

2020-11-21 17:39 UTC, merged