Feature/survey for patients
PSW-2020-ORG10/HealthcareSystem pull request #17
Opened 2020-11-26 21:58 UTC by Aleksa1998

2020-11-26 22:04 UTC, trki293 commented on PatientWebApplication/HealthClinic.DAL/Repository/IPatientsRepository.cs
> +
Unnecessarily added blank line needs to be deleted.

2020-11-26 22:05 UTC, trki293 commented on PatientWebApplication/HealthClinic.DAL/Service/ISurveyService.cs
> +
The blank line needs to be deleted.

2020-11-26 22:08 UTC, trki293 commented on PatientWebApplication/HealthClinic.DAL/Service/SurveyService.cs
> +            return CheckIfAppointmentsHappened(allValidAppointments.Where(p => !allUnvalidAppointments.Any(p2 => p2 == p.id)).ToList());
Write in the form:
"return CheckIfAppointmentsHappened(FindAllUnvalidAppointments(GetAllSurveysForPatientId(1)).Where(p => !allUnvalidAppointments.Any(p2 => p2 == p.id)).ToList());"

2020-11-26 22:08 UTC, trki293 commented on PatientWebApplication/HealthClinic.DAL/Service/SurveyService.cs
> +
The blank line needs to be deleted.

2020-11-26 22:13 UTC, trki293 commented on PatientWebApplication/PatientWebApplication/Controllers/SurveyController.cs
> +            return Ok(allValidAppointments);
Write in the form:
"return Ok(SurveyService.FindAllValidAppointments(regularAppointmentService.GetAppointmentsForPatient(1)));"

2020-11-26 22:15 UTC, trki293 requested changes
Necessary changes to the indicated places in the code.

2020-11-26 23:39 UTC, trki293 approved these changes
Good practice of Clean code satisfied, PR approved.

2020-11-27 00:31 UTC, Maja0505 approved these changes
PR is approved, all Clean code principles are followed.

2020-11-27 00:32 UTC, merged