Feature/cancel appointments
PSW-2020-ORG10/HealthcareSystem pull request #32
Opened 2020-12-05 21:32 UTC by Aleksa1998

2020-12-05 21:39 UTC, trki293 commented on PatientWebApplication/HealthClinic.DAL/Service/RegularAppointmentService.cs
> +            return _appointmentRepository.CancelAppointment(appointment);
Write return in the form of a ternary operator.

2020-12-05 21:40 UTC, trki293 commented on PatientWebApplication/PatientWebApplication/Controllers/DoctorAppointmentController.cs
> +            return Ok(appointment);
Write return in the form of a ternary operator.

2020-12-05 21:42 UTC, trki293 commented on PatientWebApplication/PatientWebApplication/Validators/AppointmentValidator.cs
> +            RuleFor(a => a.referral).Empty();*/
Delete annotated code.

2020-12-05 21:45 UTC, trki293 requested changes
Correct the indicated code sections.

2020-12-05 22:30 UTC, trki293 approved these changes
PR is approved.

2020-12-06 12:22 UTC, Maja0505 approved these changes
PR is approved. Good Clean code principles were implemented.

2020-12-06 13:03 UTC, merged