Feature/tender
PSW-2020-ORG10/HealthcareSystem pull request #48
Opened 2021-01-02 16:05 UTC by tamaragovorcin

2021-01-04 23:19 UTC, trki293 commented on IntegrationWithPharmacies/FileProtocol/ReportText.cs
> +        public String getText(DateOfOrder date, Tender tender)
Forward stringBuilder as a method parameter.

2021-01-04 23:24 UTC, trki293 commented on IntegrationWithPharmacies/FileProtocol/SmptServerService.cs
> +            return stringBuilder;
Write this in one line of code.

2021-01-04 23:27 UTC, trki293 commented on IntegrationWithPharmacies/FileProtocol/SmptServerService.cs
> +                stringBuilder.Append(Environment.NewLine);
Write this in one line of code.

2021-01-04 23:43 UTC, trki293 commented on PatientWebApplication/HealthClinic.DAL/Service/MedicineWithQuantityService.cs
> +            MedicineWithQuantity MedicineWithQuantity = IMedicineWithQuantityRepository.GetAll().SingleOrDefault(medicine => CheckMedicineNameEquality(dto, medicine));
Change name of variable: MedicineWithQuantity->medicineWithQuantity

2021-01-04 23:45 UTC, trki293 commented on PatientWebApplication/HealthClinic.DAL/Service/MedicineWithQuantityService.cs
> +            return medicineWithQuantity.Description;
Write in the form of a ternary operator.

2021-01-04 23:47 UTC, trki293 requested changes
Modify the indicated places in the code.

2021-01-05 00:18 UTC, trki293 approved these changes
PR is approved. Good principles of Clean code are followed.

2021-01-05 02:02 UTC, Maja0505 approved these changes
PR is approved. Good Clean code practice are followed.

2021-01-05 02:03 UTC, merged