Feature/ia ddd value objects
PSW-2020-ORG10/HealthcareSystem pull request #58
Opened 2021-01-24 09:18 UTC by tamaragovorcin

2021-01-25 22:01 UTC, trki293 commented on IntegrationWithPharmacies/EPrescriptionApi/AbstractFactory/PharmacyFactoryHttp.cs
> +            Console.WriteLine("OVDE SAM GAAAAAAAAAAAAAAAAAAAAAA");
Eliminate unnecessary console printing.

2021-01-25 22:01 UTC, trki293 commented on IntegrationWithPharmacies/EPrescriptionApi/AbstractFactory/PharmacyHttp.cs
> +            Console.WriteLine("***************************************          TUUUUUUUUUU");
Eliminate unnecessary console printing.

2021-01-25 22:16 UTC, trki293 commented on IntegrationWithPharmacies/MedicineInformationApi/Service/MedicineInformationService.cs
> +        public IMedicineInformationRepository IMedicineWithQuantityRepository { get; }
Change name of interface IMedicineWithQuantityRepository to _medicineWithQuantityRepository.

2021-01-25 22:17 UTC, trki293 commented on IntegrationWithPharmacies/MedicineInformationApi/Service/MedicineInformationService.cs
> +        public MedicineInformationService(IMedicineInformationRepository mdicineWithQuantityRepository)
Change name of parameter to medicineWithQuantityRepository

2021-01-25 22:18 UTC, trki293 commented on IntegrationWithPharmacies/MedicineInformationApi/Service/MedicineInformationService.cs
> +            return getMedicineNames(medicines);
Write this in form:
"return getMedicineNames(MedicineWithQuantityRepository.GetAll());"

2021-01-25 22:21 UTC, trki293 commented on IntegrationWithPharmacies/PharmacyRegistrationApi/Service/RegistrationInPharmacyService.cs
> +            return null;
Write this as a ternary operator.

2021-01-25 22:22 UTC, trki293 commented on IntegrationWithPharmacies/PharmacyRegistrationApi/Service/RegistrationInPharmacyService.cs
>          public bool isApiKeyUnique(String apiKey)
Change the method name to start with an initial capital letter.

2021-01-25 22:23 UTC, trki293 commented on IntegrationWithPharmacies/PharmacyRegistrationApi/Service/RegistrationInPharmacyService.cs
>          public RegistrationInPharmacy createIRegistration(RegistrationInPharmacyDto dto)
Change the method name to start with an initial capital letter.

2021-01-25 22:24 UTC, trki293 commented on IntegrationWithPharmacies/PharmacyRegistrationApi/Service/RegistrationInPharmacyService.cs
>          {
Change the method name 'getPharmacyApiKey' to start with an initial capital letter.

2021-01-25 22:29 UTC, trki293 commented on IntegrationWithPharmacies/TenderApi/Service/MedicineForTenderingService.cs
> +                Console.WriteLine(medicineQuantity.RequiredQuantity);
Delete the line if console printing is unnecessary.

2021-01-25 22:31 UTC, trki293 commented on IntegrationWithPharmacies/TenderApi/Service/MedicineTenderOfferService.cs
> +                medicineTenderOffer.PharmacyTenderOfferId = PharmacyTenderOfferRepository.getNextTenderPharmacyOfferId();
Correct the method name 'getNextTenderPharmacyOfferId' to start with a capital letter.

2021-01-25 22:36 UTC, trki293 commented on IntegrationWithPharmacies/UrgentMedicineOrderApi/AbstractFactory/PharmacyGrpcSftp.cs
> +            return null;
Write this as a ternary operator.
Change name of method 'CretaeUrgenMedicinetOrder' to 'CreateUrgentMedicineOrder'.

2021-01-25 22:37 UTC, trki293 commented on IntegrationWithPharmacies/UrgentMedicineOrderApi/AbstractFactory/PharmacyHttp.cs
> +            return null;
Write this as a ternary operator and apply a method name change.

2021-01-25 22:39 UTC, trki293 commented on IntegrationWithPharmacies/UrgentMedicineOrderApi/Service/SmptServerService.cs
> +        public void SendEMailNotificationForUrgentOrdee(UrgentMedicineOrder urgentMedicineOrder, string pharmacyName)
Change name of method to SendEMailNotificationForUrgentOrder and apply a method name change.

2021-01-25 22:41 UTC, trki293 commented on IntegrationWithPharmacies/UrgentMedicineOrderApi/Service/SmptServerService.cs
> +            return stringBuilder.ToString();
Write this in form:
"return "Medicine is ordered from: " + pharmacyName + "\n" + "Requested medicine: " + urgentMedicineOrder.Name + ", quantity:  " + urgentMedicineOrder.Quantity + " \n";"

2021-01-25 22:42 UTC, trki293 commented on IntegrationWithPharmacies/UrgentMedicineOrderApi/Service/UrgentOrderService.cs
> +            return null;
Write this as a ternary operator.

2021-01-25 22:45 UTC, trki293 requested changes
Modify the indicated places in the code.
Note: check the method names, they should start with a capital letter.

2021-01-26 08:54 UTC, trki293 commented on IntegrationWithPharmacies/PharmacyRegistrationApi/Repository/RegistrationInPharmacyRepository.cs
>          public RegistrationInPharmacy getPharmacyApiKey(String apiKey)
Change name of method to start with upper letter.

2021-01-26 08:57 UTC, trki293 commented on IntegrationWithPharmacies/MedicineInformationApi/Service/MedicineInformationService.cs
>          public List<MedicineName> getMedicineNames(List<MedicineInformation> medicines)
Change name of method to start with upper letter.

2021-01-26 09:00 UTC, trki293 commented on IntegrationWithPharmacies/UrgentMedicineOrderApi/AbstractFactory/PharmacyGrpcSftp.cs
> +        private String CretaeUrgenMedicinetOrder(List<MedicineName> pharmaciesWithMedicine, UrgentMedicineOrder urgentMedicineOrder)
Change method name 'CretaeUrgenMedicinetOrder' to 'CreateUrgentMedicineOrder'.

2021-01-26 09:01 UTC, trki293 commented on IntegrationWithPharmacies/UrgentMedicineOrderApi/AbstractFactory/PharmacyHttp.cs
> +        private String CretaeUrgenMedicinetOrder(List<MedicineName> pharmaciesWithMedicine, UrgentMedicineOrder urgentMedicineOrder)
Change method name 'CretaeUrgenMedicinetOrder' to 'CreateUrgentMedicineOrder'.

2021-01-26 09:04 UTC, trki293 requested changes
Correct the indicated places in the code.

2021-01-26 09:32 UTC, trki293 approved these changes
PR is approved. Good Clean code practices are followed.

2021-01-26 14:12 UTC, velicko-tam approved these changes
PR is approved. Clean code principles were implemented.

2021-01-26 14:12 UTC, merged