Feature/connecting integration with db
PSW-2020-ORG10/HealthcareSystem pull request #6
Opened 2020-11-19 16:20 UTC by mladenkak

2020-11-19 17:10 UTC, trki293 commented on IntegrationWithPharmacies/Controllers/FeedbackController.cs
> +            return Ok(result);
The list of feedback can be passed as a parameter to the 'ok()' method

2020-11-19 17:11 UTC, trki293 commented on IntegrationWithPharmacies/Controllers/FeedbackController.cs
> +            return Ok(result);
The list of feedback can be passed as a parameter to the 'ok()' method

2020-11-19 17:16 UTC, trki293 commented on IntegrationWithPharmacies/Controllers/FeedbackController.cs
> +            }
The 'else' part can be ejected. It is not necessary to instantiate an object for the generated feedback.

2020-11-19 17:17 UTC, trki293 commented on IntegrationWithPharmacies/Controllers/FeedbackController.cs
> +            if(result == null)
It is not necessary to instantiate an object for published feedback.

2020-11-19 17:22 UTC, trki293 commented on IntegrationWithPharmacies/Controllers/WeatherForecastController.cs
> +            var rng = new Random();
The name of the object needs to be changed. It needs to be more understandable.

2020-11-19 17:37 UTC, trki293 commented on IntegrationWithPharmacies/Program.cs
> +        }
It is necessary to delete the main function because there is no implementation in it.

2020-11-19 17:41 UTC, trki293 commented on IntegrationWithPharmacies/Validators/ValidationFilter.cs
> +
Need to throw 'new NotImplementedException()'

2020-11-19 17:44 UTC, trki293 requested changes
The indicated errors need to be corrected.

2020-11-20 10:36 UTC, trki293 requested changes
Not all required code changes have been made. Comments should be reviewed and appropriate changes made.

2020-11-20 11:24 UTC, trki293 requested changes
It is necessary to add a deleted file to 'PatientWebApi'.

2020-11-20 11:47 UTC, Maja0505 approved these changes

2020-11-20 11:48 UTC, trki293 approved these changes
PR is approved. Good Clean code practices have been applied.

2020-11-20 11:49 UTC, merged